"""Code-writing sub-agent.

For a given :class:`ModuleSpec`, the code writer produces one or more source
files. To keep the working demo reliable without network access, we use
deterministic templates keyed by the module's ``kind``. When an LLM is
configured and produces well-formed JSON, its output is merged in — but the
deterministic templates always seed the module so the pipeline can finish
end-to-end even when all providers are unreachable (e.g. CI).
"""

from __future__ import annotations

from agentforge.logging import get_logger
from agentforge.memory import SharedContext
from agentforge.models import EngineeringSpec, ModuleArtifact, ModuleSpec
from agentforge.providers import Message, extract_json, get_provider

logger = get_logger("code_writer")


_SYSTEM_PROMPT = """You are a senior Python engineer. Produce the smallest
coherent set of files required to implement the given module in the shared
project. Respond in strict JSON:

{"files": {"relative/path.py": "file contents", ...}}

Do not wrap the JSON in prose.
<task:code>
"""


def _readme(spec: EngineeringSpec) -> str:
    return f"""# {spec.project_name}

{spec.summary}

## Generated by AgentForge

This project was assembled by AgentForge. See the accompanying
`audit_report.json` and `dependency_map.json` for a description of how the
pipeline arrived at this output.

## Running

```bash
pip install -e .
uvicorn {spec.project_name}.main:app --reload
```

## Tests

```bash
pytest -q
```
"""


def _pyproject(spec: EngineeringSpec) -> str:
    return f"""[project]
name = "{spec.project_name}"
version = "0.1.0"
description = "{spec.summary[:120].replace(chr(10), ' ')}"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110",
    "uvicorn>=0.27",
    "sqlalchemy>=2.0",
    "pydantic>=2.6",
    "passlib[bcrypt]>=1.7",
    "bcrypt<4.1",
    "python-jose[cryptography]>=3.3",
    "python-multipart>=0.0.9",
]

[project.optional-dependencies]
dev = ["pytest>=8.0", "httpx>=0.27"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
"""


def _database_module(spec: EngineeringSpec) -> dict[str, str]:
    return {
        f"{spec.project_name}/database.py": '''"""Database session and engine."""

from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

DATABASE_URL = "sqlite:///./app.db"

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},
    future=True,
)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    """Base class for all ORM models."""


def get_db() -> Session:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    """Create tables for all registered models."""
    # Import side-effects register the models.
    from . import models  # noqa: F401

    Base.metadata.create_all(bind=engine)
''',
        f"{spec.project_name}/models.py": '''"""ORM models."""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, nullable=False)

    todos: Mapped[list["Todo"]] = relationship(back_populates="owner", cascade="all, delete-orphan")


class Todo(Base):
    __tablename__ = "todos"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(String(1024), default="", nullable=False)
    done: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, nullable=False)

    owner: Mapped[User] = relationship(back_populates="todos")
''',
    }


def _auth_module(spec: EngineeringSpec) -> dict[str, str]:
    return {
        f"{spec.project_name}/auth.py": '''"""Authentication utilities: password hashing and JWT tokens."""

from __future__ import annotations

import os
from datetime import datetime, timedelta, timezone
from typing import Any

from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from passlib.context import CryptContext
from sqlalchemy.orm import Session

from .database import get_db
from .models import User

# Read the secret from the environment; fall back to a clearly-flagged dev
# value so local tests succeed. Production deployments MUST set APP_SECRET.
SECRET_KEY = os.environ.get("APP_SECRET", "dev-only-insecure-secret-change-me")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login")


def hash_password(password: str) -> str:
    return pwd_context.hash(password)


def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)


def create_access_token(subject: str, expires_delta: timedelta | None = None) -> str:
    to_encode: dict[str, Any] = {"sub": subject}
    expire = datetime.now(timezone.utc) + (
        expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    to_encode["exp"] = expire
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(
    token: str = Depends(oauth2_scheme),
    db: Session = Depends(get_db),
) -> User:
    credentials_exc = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email = payload.get("sub")
        if not isinstance(email, str):
            raise credentials_exc
    except JWTError as exc:
        raise credentials_exc from exc
    user = db.query(User).filter(User.email == email).first()
    if user is None:
        raise credentials_exc
    return user
''',
    }


def _api_module(spec: EngineeringSpec) -> dict[str, str]:
    return {
        f"{spec.project_name}/schemas.py": '''"""Pydantic schemas for request and response bodies."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class UserCreate(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)


class UserOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    email: EmailStr
    created_at: datetime


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class TodoCreate(BaseModel):
    title: str = Field(min_length=1, max_length=255)
    description: str = Field(default="", max_length=1024)


class TodoUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=255)
    description: str | None = Field(default=None, max_length=1024)
    done: bool | None = None


class TodoOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    description: str
    done: bool
    created_at: datetime
''',
        f"{spec.project_name}/main.py": f'''"""FastAPI application entrypoint for {spec.project_name}."""

from __future__ import annotations

from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session

from .auth import (
    create_access_token,
    get_current_user,
    hash_password,
    verify_password,
)
from .database import get_db, init_db
from .models import Todo, User
from .schemas import (
    Token,
    TodoCreate,
    TodoOut,
    TodoUpdate,
    UserCreate,
    UserOut,
)

app = FastAPI(title="{spec.project_name}")


@app.on_event("startup")
def _startup() -> None:
    init_db()


@app.post("/auth/signup", response_model=UserOut, status_code=status.HTTP_201_CREATED)
def signup(payload: UserCreate, db: Session = Depends(get_db)) -> User:
    existing = db.query(User).filter(User.email == payload.email).first()
    if existing is not None:
        raise HTTPException(status_code=400, detail="Email already registered")
    user = User(email=payload.email, hashed_password=hash_password(payload.password))
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@app.post("/auth/login", response_model=Token)
def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
) -> Token:
    user = db.query(User).filter(User.email == form_data.username).first()
    if user is None or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    return Token(access_token=create_access_token(subject=user.email))


@app.get("/auth/me", response_model=UserOut)
def me(current_user: User = Depends(get_current_user)) -> User:
    return current_user


@app.get("/todos", response_model=list[TodoOut])
def list_todos(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> list[Todo]:
    return (
        db.query(Todo)
        .filter(Todo.owner_id == current_user.id)
        .order_by(Todo.created_at.desc())
        .all()
    )


@app.post("/todos", response_model=TodoOut, status_code=status.HTTP_201_CREATED)
def create_todo(
    payload: TodoCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Todo:
    todo = Todo(
        title=payload.title,
        description=payload.description,
        owner_id=current_user.id,
    )
    db.add(todo)
    db.commit()
    db.refresh(todo)
    return todo


@app.get("/todos/{{todo_id}}", response_model=TodoOut)
def get_todo(
    todo_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Todo:
    todo = db.query(Todo).filter(Todo.id == todo_id, Todo.owner_id == current_user.id).first()
    if todo is None:
        raise HTTPException(status_code=404, detail="Todo not found")
    return todo


@app.patch("/todos/{{todo_id}}", response_model=TodoOut)
def update_todo(
    todo_id: int,
    payload: TodoUpdate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Todo:
    todo = db.query(Todo).filter(Todo.id == todo_id, Todo.owner_id == current_user.id).first()
    if todo is None:
        raise HTTPException(status_code=404, detail="Todo not found")
    data = payload.model_dump(exclude_unset=True)
    for key, value in data.items():
        setattr(todo, key, value)
    db.commit()
    db.refresh(todo)
    return todo


@app.delete("/todos/{{todo_id}}", status_code=status.HTTP_204_NO_CONTENT)
def delete_todo(
    todo_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> None:
    todo = db.query(Todo).filter(Todo.id == todo_id, Todo.owner_id == current_user.id).first()
    if todo is None:
        raise HTTPException(status_code=404, detail="Todo not found")
    db.delete(todo)
    db.commit()
''',
        f"{spec.project_name}/__init__.py": '"""Generated package."""\n',
    }


def _security_module(spec: EngineeringSpec) -> dict[str, str]:
    return {
        f"{spec.project_name}/security.py": '''"""Security middleware: headers, basic rate limiting."""

from __future__ import annotations

import time
from collections import defaultdict, deque
from typing import Callable

from fastapi import FastAPI, HTTPException, Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Attach a baseline set of security headers to every response."""

    HEADERS = {
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "Referrer-Policy": "no-referrer",
        "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
        "Content-Security-Policy": "default-src 'self'",
    }

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        response = await call_next(request)
        for key, value in self.HEADERS.items():
            response.headers.setdefault(key, value)
        return response


class InMemoryRateLimiter(BaseHTTPMiddleware):
    """Very small fixed-window rate limiter for dev/demo use."""

    def __init__(self, app, *, requests_per_minute: int = 120) -> None:
        super().__init__(app)
        self.rpm = requests_per_minute
        self._hits: dict[str, deque[float]] = defaultdict(deque)

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        now = time.monotonic()
        ip = request.client.host if request.client else "unknown"
        window = self._hits[ip]
        while window and now - window[0] > 60:
            window.popleft()
        if len(window) >= self.rpm:
            raise HTTPException(status_code=429, detail="Too Many Requests")
        window.append(now)
        return await call_next(request)


def install(app: FastAPI) -> None:
    """Attach security middleware to the FastAPI app."""
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(InMemoryRateLimiter)
''',
    }


def _docs_module(spec: EngineeringSpec) -> dict[str, str]:
    return {
        "README.md": _readme(spec),
        "pyproject.toml": _pyproject(spec),
    }


_TEMPLATES = {
    "database": _database_module,
    "auth": _auth_module,
    "api": _api_module,
    "security": _security_module,
    "docs": _docs_module,
}


def run(spec: EngineeringSpec, module: ModuleSpec, context: SharedContext) -> ModuleArtifact:
    """Produce a :class:`ModuleArtifact` for *module*."""

    files: dict[str, str] = {}
    template = _TEMPLATES.get(module.kind)
    if template is not None:
        files.update(template(spec))

    # Try the LLM too; merge any new files it proposes.
    provider = get_provider()
    try:
        raw = provider.complete(
            [
                Message(role="system", content=_SYSTEM_PROMPT),
                Message(
                    role="user",
                    content=(
                        f"Project: {spec.project_name}\n"
                        f"Module: {module.name} ({module.kind})\n"
                        f"Description: {module.description}\n"
                        f"Acceptance criteria: {module.acceptance_criteria}\n"
                        f"Target stack: {spec.target_stack}\n"
                    ),
                ),
            ],
            temperature=0.2,
        )
        data = extract_json(raw)
        for path, content in (data.get("files") or {}).items():
            if path not in files and isinstance(content, str):
                files[path] = content
    except Exception as exc:
        logger.debug("code_writer LLM call skipped: %s", exc)

    artifact = ModuleArtifact(
        module=module.name,
        agent="code_writer",
        files=files,
        notes=f"Generated {len(files)} files for module {module.name} ({module.kind}).",
    )
    context.audit(
        "code_writer",
        "module_built",
        {"module": module.name, "files": list(files.keys())},
    )
    for path in files:
        context.remember(
            f"code_writer produced {path} for {module.name}",
            metadata={"module": module.name, "file": path, "kind": module.kind},
        )
    return artifact
